/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2019-12-12-f58bda6"
#endif /* AVUTIL_FFVERSION_H */
